### ISSUE TITLE
Pointz not loading with spigot 1.12.2

### ISSUE THREAD

**Issue by tanguy-fgl** [nivcoo/Spigot-Pointz#4]
[13:30:52 INFO]: [Pointz] Enabling Pointz v2.0.0

> [13:30:52 INFO]: =============================

> [13:30:52 INFO]: Pointz v2.0.0

> [13:30:52 INFO]: Database: No !

> [13:30:52 INFO]: Plugin-Pointz: No !

> [13:30:52 INFO]:

> [13:30:52 INFO]: Plugin Disabled !

> [13:30:52 INFO]: =============================

> [13:30:52 INFO]: [Pointz] Disabling Pointz v2.0.0

**Comment by nivcoo** [comment]
C'est pas la peine d'ouvrir une issue pour ça j'avais dis sur discord de regarder les logs, la le plugin n'est pas liée a la base de donnée, si ça ne marche pas c'est que les infos ne sont pas bonne ou que le serveur n'a pas accès a la bdd

**Comment by tanguy-fgl** [comment]
Comment est-ce que le plugin se connecte à la base de donnée?
