### ISSUE TITLE
erreur console

### ISSUE THREAD

**Issue by Bobbbe** [nivcoo/Spigot-Pointz#5]
https://pastebin.com/hC0FmCH6
J'ai ceci quand je tape /pshop

**Comment by Bobbbe** [comment]
je vois que tu as une mise a jour de fait 2.0.1 mais sur spigot il y a que la 2.0.0 et ici ou est le pointz.jar ? je pourrais l'essayer ?

**Comment by nivcoo** [comment]
C'est fixe en 2.0.5
